# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc6978dc124bce67c5758b9a767aa69182bb1d46b6163cd1fee5c29dc1a188ecd24c6a8f770bc2b94e2bf112d0024b67455c22149cc4649bf05409cbe607eba4

test:
  secret_key_base: e7ab21da3a70bc412af8df99d513541ca0c4f8df5076e9962594c7344a132779dd1f74643eb8890035ca31ca8e5a7943ab9a8e5a6150e2beff75845ce46991a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
